### ISSUE TITLE
re indexing not works

### ISSUE THREAD

**Issue by veeruborra** [codelibs/elasticsearch-reindexing#15]
I created a index with mappings and stored 3020 documents in it.
Now i created another index with mappins and changed type for one field.Now i am trying to move only data from oldindex to newindex.After the process completes no data is shown in new index.

curl -XPOST localhost:9200/admin_logs421/_reindex/admin_logs422?wait_for_completion=true

the error is 

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"}],"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"},"status":400}

**Comment by marevol** [comment]
Please check elasticsearch's log file.

**Comment by jramos** [comment]
Having the same issue with 2.1.1.

```
[2016-01-25 01:04:21,841][INFO ][rest.suppressed          ] /oldindex/_reindex/newindex/
Params: {id=newindex, index=oldindex, type=_reindex}
RemoteTransportException[[Aleksander Lukin][172.31.7.244:9300][indices:data/write/index]]; nested: MapperParsingException[failed to parse, document is empty];
Caused by: MapperParsingException[failed to parse, document is empty]
        at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:156)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:551)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:542)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1049)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by marevol** [comment]
Installation of Reindexing Plugin seems to be failed.
> Params: {id=newindex, index=oldindex, type=_reindex}

elasticsearch handles _reindex as type.
Please check if the plugin is installed correctly.

**Comment by jramos** [comment]
I installed 2.1.1 as a plugin in ES 2.1.1.

```
$ bin/plugin list
Installed plugins in /home/hadoop/elasticsearch/elasticsearch-2.1.1/plugins:
    - kopf
    - reindexing
    - repository-hdfs
    - cloud-aws
    - hq

$ curl -XGET 'http://ip-172-31-12-242:9200/_reindex'
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No feature for name [_reindex]"}],"type":"illegal_argument_exception","reason":"No feature for name [_reindex]"},"status":400}
```

**Comment by marevol** [comment]
See:
https://www.elastic.co/guide/en/elasticsearch/reference/2.x/cat-plugins.html

**Comment by jramos** [comment]
Ah. I had to restart ES master, then it started working.
