### ISSUE TITLE
REST URL not recognised?

### ISSUE THREAD

**Issue by pugnascotia** [codelibs/elasticsearch-reindexing#18]
ES Version: 1.7.0
Plugin: 2.1.1

When I try to execute a reindex using curl:

    curl -XPOST localhost:9200/testindex/_reindex/newtestindex/

I get the following error:

    {"error":"InvalidTypeNameException[mapping type name [_reindex] can't start with '_']","status":400}

In the logs there is:

```
[2016-02-18 09:32:26,828][DEBUG][action.index             ] [Skids] [testindex][0], node[3jMGLvmpQemPzzvyJHVPPA], [P], s[STARTED]: Failed to execute [index {[testindex][_reindex][newtestindex], source[_na_]}]
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_reindex] can't start with '_'
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:307)
	at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:482)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:491)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:192)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marevol** [comment]
See elasticsearch's log file.
I think reindexing plugin installation is failed.

**Comment by pugnascotia** [comment]
I found this in the logs:

    [2016-02-18 10:23:42,989][DEBUG][plugins                  ] [Forbush Man] [/usr/share/elasticsearch/plugins/reindexing/_site] directory does not exist.
    [2016-02-18 10:23:42,989][INFO ][plugins                  ] [Forbush Man] loaded [], sites []

I tried installing in ES 2, which worked:

    [2016-02-18 10:32:05,823][INFO ][plugins                  ] [Namorita] modules [lang-expression, lang-groovy], plugins [reindexing], sites []

**Comment by marevol** [comment]
Plugins of version 2.x does not work on elasticsearch 1.x.
Please use version 1.7.0.

**Comment by sharadkhandelwal** [comment]
I am having the same problem even with compatible versions:

ES Version: 1.7.1
Plugin Version: 1.7.0

Exception:
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_reindex] can't start with '_'

**Comment by marevol** [comment]
I think plugin installation was failed.
